### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by felddy**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-python-library.git`](https://github.com/cisagov/skeleton-python-library.git)

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by felddy** [comment]
Why you no changes?!  

Because the new Lineage will no longer allow genterated PRs to change a repository's`.github/lineage.yml` file.  It will protects the file during the merge, and resolves any conflicts as `--ours`.

You'll see weirdness like this when it happens, as the no-op PR.  Fun!

**Review by jsf9k — APPROVED** [review]
Minimalistic.  Bold.  I like it.

**Comment by felddy** [comment]
GavinB

**Review by dav3r — APPROVED** [review]
The greatest trick the Devil ever pulled was convincing the world he didn’t exist.

**Review by mcdonnnj — APPROVED** [review]
Bold. Decisive. I like it.

**Pull request merged**
